import { writeFile } from 'node:fs/promises'
import { Command } from 'commander'
import chalk from 'chalk'
import inquirer from 'inquirer'
import ora from 'ora'
import { installSkills, recommendSkills, runPlanningPipeline } from '@ai-planner/core'
import type { PlanningProgress, PlanningRunOptions } from '@ai-planner/core'
import { resolveTargetAgentContext } from '../agent.js'
import { promptSkillSelection } from '../prompts.js'

/**
 * `aip new`
 * Plan a new project, save the plan locally, recommend skills, and install locally.
 */
export const newCommand = new Command('new')
  .description('Plan a new project locally with gstack-backed workflows and prepare the local agent environment')
  .option('-a, --agent <agent>', 'Target agent')
  .option('--output <file>', 'Save implementation plan to file', 'implementation_plan.md')
  .action(async (opts: { agent?: string; output: string }) => {
    const agentContext = await resolveTargetAgentContext(opts.agent)
    const targetAgent = agentContext.agent

    console.log(chalk.bold.cyan('\nAI Planner Local - New Project\n'))
    console.log(chalk.dim(`Target agent resolved to ${targetAgent} (${describeAgentSource(agentContext.source)})`))

    const { description } = await inquirer.prompt([
      {
        type: 'editor',
        name: 'description',
        message: 'Describe your project idea (opens editor):',
        default: '## Project Idea\n\nDescribe what you want to build here...\n\n## Target Users\n\n## Key Features\n',
      },
    ])

    if (!description?.trim()) {
      console.log(chalk.yellow('No description provided. Exiting.'))
      return
    }

    console.log(chalk.bold('\nRunning local planning pipeline...\n'))

    const planSpinner = ora({ text: 'Running /office-hours...', prefixText: '[1/4]' }).start()
    const planningOptions: PlanningRunOptions = {
      agent: targetAgent,
      onProgress: (progress: PlanningProgress) => {
        const steps = ['office-hours', 'ceo-review', 'eng-review', 'design-review']
        const stepIndex = steps.indexOf(progress.currentStep) + 1
        const stepLabels: Record<string, string> = {
          'office-hours': 'Running /office-hours - product reframe',
          'ceo-review': 'Running /plan-ceo-review - scope review',
          'eng-review': 'Running /plan-eng-review - architecture review',
          'design-review': 'Running /plan-design-review - UX review',
        }
        planSpinner.prefixText = `[${stepIndex}/4]`
        planSpinner.text = stepLabels[progress.currentStep] ?? progress.currentStep
      },
    }

    const result = await runPlanningPipeline(description, planningOptions)

    planSpinner.succeed(chalk.green('Planning complete'))

    const planContent = `# Implementation Plan\n\n_Generated by AI Planner on ${new Date().toLocaleDateString()}_\n\n${result.designDoc}`
    await writeFile(opts.output, planContent, 'utf-8')
    console.log(chalk.dim(`\nPlan saved to: ${opts.output}`))

    if (result.techStack.length > 0) {
      console.log(chalk.bold(`\nTech stack from plan: ${result.techStack.join(', ')}`))
    }

    const skillSpinner = ora('Finding relevant skills...').start()
    const projectContext = `New project: ${description.substring(0, 200)}`

    try {
      const recommendations = await recommendSkills(result.techStack, projectContext)
      skillSpinner.succeed(chalk.green(`Found ${recommendations.length} skill recommendations`))

      if (recommendations.length === 0) {
        console.log(chalk.yellow('\nNo skills matched. Use: aip skills add <repo> to add manually'))
        return
      }

      const selected = await promptSkillSelection(recommendations)
      if (selected.length === 0) {
        console.log(chalk.yellow('\nNo skills selected. Done.'))
        return
      }

      const installSpinner = ora(`Installing ${selected.length} skills for ${targetAgent}...`).start()
      const installResult = await installSkills(
        selected.map((recommendation) => ({
          repo: recommendation.skill.repo,
          name: recommendation.skill.id,
          source: recommendation.skill.source,
          sourcePath: recommendation.skill.sourcePath,
        })),
        targetAgent
      )

      if (installResult.success.length > 0) {
        installSpinner.succeed(chalk.green(`Installed: ${installResult.success.join(', ')}`))
      }
      if (installResult.failed.length > 0) {
        installSpinner.warn(chalk.yellow(`Failed: ${installResult.failed.join(', ')}`))
      }

      console.log(chalk.bold.green('\nLocal project planning is ready.'))
      console.log(chalk.dim(`  - Plan file: ${opts.output}`))
      console.log(chalk.dim(`  - Target agent: ${targetAgent} (${describeAgentSource(agentContext.source)})`))
      console.log(chalk.dim(`  - Installed skills: ${installResult.success.length}`))
      console.log(chalk.dim('  - Next step: review the saved plan and start building with your local agent\n'))
    } catch (err) {
      skillSpinner.fail('Skill recommendation failed')
      console.error(chalk.red(String(err)))
    }
  })

function describeAgentSource(source: 'explicit' | 'config' | 'default'): string {
  if (source === 'explicit') return 'from --agent'
  if (source === 'config') return 'from .aiplanner.json defaultAgent'
  return 'from built-in default'
}
