import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import type { PlannerEngine, PlannerInput, PlannerProgress } from './types.js'
import type { PlanningResult, PlanningRuntimeInfo } from '../types.js'
import { directLlmPlanner } from './direct-llm.js'
import { extractPlanningTech, extractSection } from '../utils/tech-extractor.js'

const execFileAsync = promisify(execFile)

export const gstackPlanner: PlannerEngine = {
  id: 'gstack',
  name: 'gstack skills',

  async isAvailable(agent: string): Promise<boolean> {
    try {
      const { stdout } = await execFileAsync('npx', ['skills', 'list', '-a', agent], {
        timeout: 5000,
        shell: true,
      })
      return hasGstackSkillsInstalled(stdout)
    } catch {
      return false
    }
  },

  async install(options: { agent: string; scope: 'global' | 'local' }): Promise<void> {
    try {
      await execFileAsync('npx', ['skills', 'add', 'garrytan/gstack', '-a', options.agent, '-y'], {
        timeout: 60000,
        shell: true,
      })
    } catch (e) {
      console.warn(`gstack install failed for ${options.agent} - will use LLM fallback for planning skills`)
      throw e
    }
  },

  async plan(input: PlannerInput): Promise<PlanningResult> {
    const targetAgent = input.agent ?? 'antigravity'
    
    // Ensure installed if requested implicitly
    if (!(await this.isAvailable(targetAgent))) {
      await this.install({ agent: targetAgent, scope: 'local' })
    }

    const steps: PlannerProgress['steps'] = [
      { name: 'office-hours', status: 'pending' },
      { name: 'ceo-review', status: 'pending' },
      { name: 'eng-review', status: 'pending' },
      { name: 'design-review', status: 'pending' },
    ]

    let accumulatedOutput = ''
    let usedGstack = false
    let usedDirectLLM = false

    const updateProgress = (stepName: string, status: 'running' | 'done' | 'error', output = '') => {
      const step = steps.find((s: any) => s.name === stepName)
      if (step) step.status = status
      if (output) accumulatedOutput += output
      input.onProgress?.({
        currentStep: stepName,
        steps: [...steps],
        output: accumulatedOutput,
      })
    }

    const runGstackSkill = async (skillName: string, inputData: string): Promise<string> => {
      try {
        const { stdout, stderr } = await execFileAsync(
          'npx',
          ['skills', 'run', `garrytan/gstack:${skillName}`, '--input', inputData],
          { timeout: 60000, shell: true }
        )

        const combinedOutput = `${stdout ?? ''}\n${stderr ?? ''}`.trim()
        if (!combinedOutput || isInvalidGstackOutput(combinedOutput)) {
          throw new Error(`gstack skill ${skillName} returned invalid output`)
        }

        return stdout
      } catch {
        usedDirectLLM = true
        // If gstack fails, we do a direct LLM call logic inline or delegate to direct LLM planner logic
        // But for simplicity, we mock running the skill via LLM by calling directLlm's logic.
        // As a shortcut, we just throw to use fallback for simple cases or parse it fully.
        throw new Error('Gstack execution failed')
      }
    }

    // Since direct LLM planner already has all logic, if gstack fails step 1, 
    // it's easier to just use the LLM logic from the existing orchestrator:
    const { callLLM } = await import('../llm/provider.js')
    
    const fallbackRunSkillViaLLM = async (skillName: string, inputData: string): Promise<string> => {
      const skillInstructions: Record<string, string> = {
        'office-hours': "You are running a YC-style office hours session. Ask 6 forcing questions...",
        'plan-ceo-review': "You are a CEO reviewing a product plan...",
        'plan-eng-review': "You are an experienced engineering manager...",
        'plan-design-review': "You are a senior product designer..."
      }
      const instructions = skillInstructions[skillName] ?? `Run ${skillName}`
      const response = await callLLM([{ role: 'system', content: instructions }, { role: 'user', content: inputData }], { maxTokens: 3000 })
      return `<!-- Generated by direct LLM fallback: ${response.provider}/${response.model} -->\n${response.text}`
    }

    const runSkillWithFallback = async (skillName: string, inputData: string): Promise<string> => {
      try {
        const out = await runGstackSkill(skillName, inputData)
        usedGstack = true
        return out
      } catch {
        usedDirectLLM = true
        return fallbackRunSkillViaLLM(skillName, inputData)
      }
    }

    updateProgress('office-hours', 'running')
    let officeHoursOutput = ''
    try {
      officeHoursOutput = await runSkillWithFallback('office-hours', input.description)
      updateProgress('office-hours', 'done', officeHoursOutput)
    } catch {
      updateProgress('office-hours', 'error')
      officeHoursOutput = `# Design Doc\n\n## Project Description\n${input.description}\n`
    }

    updateProgress('ceo-review', 'running')
    let ceoOutput = ''
    try {
      ceoOutput = await runSkillWithFallback('plan-ceo-review', officeHoursOutput)
      updateProgress('ceo-review', 'done', ceoOutput)
    } catch {
      updateProgress('ceo-review', 'error')
    }

    updateProgress('eng-review', 'running')
    let engOutput = ''
    try {
      engOutput = await runSkillWithFallback('plan-eng-review', `${officeHoursOutput}\n${ceoOutput}`)
      updateProgress('eng-review', 'done', engOutput)
    } catch {
      updateProgress('eng-review', 'error')
    }

    updateProgress('design-review', 'running')
    let designOutput = ''
    try {
      designOutput = await runSkillWithFallback('plan-design-review', engOutput)
      updateProgress('design-review', 'done', designOutput)
    } catch {
      updateProgress('design-review', 'error')
    }

    const fullOutput = [officeHoursOutput, ceoOutput, engOutput, designOutput].join('\n\n---\n\n')

    // tech extraction
    const promptSignals = extractPlanningTech(input.description, { trustGenericFrameworkMentions: true })
    const outputSignals = extractPlanningTech(fullOutput, { trustGenericFrameworkMentions: false })
    const techStack = Array.from(new Set([...promptSignals, ...outputSignals]))

    const fallbackMatch = fullOutput.match(/Generated by direct LLM fallback:\s*([a-z]+)\/([^\s>]+)/i)
    const provider = fallbackMatch?.[1] as any
    const model = fallbackMatch?.[2]

    let mode: PlanningRuntimeInfo['mode'] = 'gstack'
    if (usedGstack && usedDirectLLM) mode = 'mixed'
    else if (usedDirectLLM) mode = 'direct-llm'

    return {
      designDoc: fullOutput,
      techStack,
      architecture: extractSection(fullOutput, 'architecture'),
      timeline: extractSection(fullOutput, 'timeline'),
      skillSuggestions: techStack,
      runtime: { mode, provider, model },
    }
  },
}

function hasGstackSkillsInstalled(output: string): boolean {
  const normalized = output.toLowerCase()
  return ['garrytan/gstack', 'office-hours'].some((token) => normalized.includes(token))
}

function isInvalidGstackOutput(output: string): boolean {
  const normalized = output.toLowerCase()
  return [
    'unknown command: run',
    'run skills --help for usage',
    'command not found',
    'not recognized as the name of a cmdlet',
  ].some((token) => normalized.includes(token))
}
